dist: xenial
language: c++
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/ccache

addons:
  apt:
    packages:
      - libeigen3-dev
      - libhdf5-dev
      - libgflags-dev
      - libspdlog-dev

before_install:
  - git submodule update --init --recursive

install:
  - mkdir build
  - cd build/
  - cmake ../

script: make -j
